//===- CppInterOpEmitter.cpp - Emit X-macro .inc from .td records ---------===//
//
// Part of the compiler-research project, under the Apache License v2.0 with
// LLVM Exceptions.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Emits a single CppInterOpAPI.inc file. Each API function becomes one
// CPPINTEROP_API_FUNC invocation that consumers expand with their own macro
// definition.
//
//   CPPINTEROP_API_FUNC(DispatchName, CppName, ReturnType,
//                       DeclArgs, CallArgs, RawArgTypes, Defaults)
//
// where:
//   DispatchName  — name in the dispatch table (unique, even for overloads)
//   CppName       — name in CppImpl:: namespace (may be shared by overloads)
//   ReturnType    — C++ return type string
//   DeclArgs      — "(Type1 name1, Type2 name2, ...)" with defaults
//   CallArgs      — "(name1, name2, ...)" for forwarding
//   RawArgTypes   — "(Type1, Type2, ...)" for function pointer declarations
//
//===----------------------------------------------------------------------===//

#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TableGen/Record.h"

#include <utility>
#include <vector>

using namespace llvm;

namespace {

struct ArgInfo {
  StringRef Type;
  StringRef Name;
  StringRef Default;
};

struct APIRecord {
  StringRef Name;
  StringRef CppName;
  StringRef DispatchName;
  StringRef ReturnType;
  StringRef Doc;
  std::vector<ArgInfo> Args;
};

std::vector<APIRecord> collectAPIs(const RecordKeeper& Records) {
  std::vector<APIRecord> APIs;
  for (const auto* Rec : Records.getAllDerivedDefinitions("CppInterOpAPI")) {
    APIRecord R;
    R.Name = Rec->getName();
    R.CppName = Rec->getValueAsString("CppName");
    R.DispatchName = Rec->getValueAsString("DispatchName");
    R.ReturnType = Rec->getValueAsString("ReturnType");
    R.Doc = Rec->getValueAsString("Doc");
    for (const auto* ArgRec : Rec->getValueAsListOfDefs("Args")) {
      ArgInfo A;
      A.Type = ArgRec->getValueAsString("Type");
      A.Name = ArgRec->getValueAsString("Name");
      A.Default = ArgRec->getValueAsString("Default");
      R.Args.push_back(A);
    }
    APIs.push_back(std::move(R));
  }
  return APIs;
}

} // end anonymous namespace

void EmitCppInterOpAPI(const RecordKeeper& Records, raw_ostream& OS) {
  OS << "// Auto-generated by cppinterop-tblgen. Do not edit.\n";
  OS << "//\n";
  OS << "// Each entry expands CPPINTEROP_API_FUNC(DispatchName, CppName,\n";
  OS << "//   ReturnType, DeclArgs, CallArgs, RawArgTypes)\n";
  OS << "//\n";
  OS << "// Define CPPINTEROP_API_FUNC before including this file, then\n";
  OS << "// #undef it afterward.\n";
  OS << "\n";
  OS << "#ifndef CPPINTEROP_API_FUNC\n";
  OS << "#error \"Define CPPINTEROP_API_FUNC before including "
        "CppInterOpAPI.inc\"\n";
  OS << "#endif\n\n";

  for (const auto& R : collectAPIs(Records)) {
    OS << "CPPINTEROP_API_FUNC(" << R.DispatchName << ", " << R.CppName << ", "
       << R.ReturnType << ", ";

    // DeclArgs: (Type name = default, ...)
    OS << "(";
    for (size_t I = 0; I < R.Args.size(); ++I) {
      if (I)
        OS << ", ";
      OS << R.Args[I].Type << " " << R.Args[I].Name;
      if (!R.Args[I].Default.empty())
        OS << " = " << R.Args[I].Default;
    }
    OS << "), ";

    // CallArgs: (name, ...)
    OS << "(";
    for (size_t I = 0; I < R.Args.size(); ++I) {
      if (I)
        OS << ", ";
      OS << R.Args[I].Name;
    }
    OS << "), ";

    // RawArgTypes: (Type, ...)
    OS << "(";
    for (size_t I = 0; I < R.Args.size(); ++I) {
      if (I)
        OS << ", ";
      OS << R.Args[I].Type;
    }
    OS << "))\n";
  }

  OS << "\n#undef CPPINTEROP_API_FUNC\n";
}

void EmitCppInterOpDecl(const RecordKeeper& Records, raw_ostream& OS) {
  OS << "// Auto-generated by cppinterop-tblgen. Do not edit.\n";
  OS << "// Function declarations for the CppInterOp public API.\n\n";

  for (const auto& R : collectAPIs(Records)) {
    // Emit doxygen comment if present.
    if (!R.Doc.empty()) {
      // Split multi-line doc strings and prefix each with ///.
      SmallVector<StringRef, 4> Lines;
      R.Doc.split(Lines, '\n');
      for (const auto& Line : Lines) {
        StringRef Trimmed = Line.ltrim();
        if (Trimmed.empty())
          OS << "///\n";
        else
          OS << "/// " << Trimmed << "\n";
      }
    }

    // Emit the declaration.
    OS << "CPPINTEROP_API " << R.ReturnType << " " << R.CppName << "(";
    for (size_t I = 0; I < R.Args.size(); ++I) {
      if (I)
        OS << ", ";
      OS << R.Args[I].Type << " " << R.Args[I].Name;
      if (!R.Args[I].Default.empty())
        OS << " = " << R.Args[I].Default;
    }
    OS << ");\n\n";
  }
}
