//===--- CppInterOp.h - A layer for language interoperability ---*- C++ -*-===//
//
// Part of the compiler-research project, under the Apache License v2.0 with
// LLVM Exceptions.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file defines API for introspection which enables language
// interoperability.
//
//===----------------------------------------------------------------------===//

#ifndef CPPINTEROP_CPPINTEROP_H
#define CPPINTEROP_CPPINTEROP_H

#ifdef CPPINTEROP_DISPATCH_H
#error "CppInterOp.h and Dispatch.h are mutually exclusive — include only one."
#endif

#include "CppInterOp/CppInterOpTypes.h"

#include <initializer_list>
#include <memory>
#include <utility>
#include <vector>

namespace CppImpl {

// Public API function declarations. Generated by cppinterop-tblgen
// from CppInterOp.td. Do not edit this section by hand.
#include "CppInterOp/CppInterOpDecl.inc"

struct VTableOverlayDeleter {
  void operator()(VTableOverlay* o) const noexcept { DestroyVTableOverlay(o); }
};
using UniqueVTableOverlay =
    std::unique_ptr<VTableOverlay, VTableOverlayDeleter>;

/// Owning wrapper over MakeVTableOverlay: each pair maps a virtual method
/// of polymorphic class \c base to its replacement function pointer. The
/// overlay is installed on construction and the original vptr restored when
/// the handle is destroyed. The caller works in reflected methods, not
/// ABI-specific slot indices -- the common path for language bindings.
inline UniqueVTableOverlay MakeUniqueVTableOverlay(
    void* inst, TCppScope_t base,
    std::initializer_list<std::pair<TCppConstFunction_t, void*>> overrides) {
  std::vector<TCppConstFunction_t> methods;
  std::vector<void*> fns;
  methods.reserve(overrides.size());
  fns.reserve(overrides.size());
  for (const auto& p : overrides) {
    methods.push_back(p.first);
    fns.push_back(p.second);
  }
  return UniqueVTableOverlay{MakeVTableOverlay(inst, base, methods.data(),
                                               fns.data(), methods.size())};
}

} // namespace CppImpl

// NOLINTNEXTLINE(misc-unused-alias-decls)
namespace Cpp = CppImpl;
#endif // CPPINTEROP_CPPINTEROP_H
